load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/warehouse.csv into warehouse;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/item.csv into item;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/stock.csv into stock;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/district.csv into district;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/customer.csv into customer;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/history.csv into history;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/orders.csv into orders;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/new_orders.csv into new_orders;
load /home/bobby_ubuntu/Git/Git/MyProjects/Database/db2025/rmdb/test/tpcc_generate_data/tpcc_csv/order_line.csv into order_line;
